### PR TITLE
fix(Memory): bounds check, alignment checks, exceptions & cleanup

### LINKED ISSUE #191: fix: Memory.cpp bounds check, alignment checks, and small changes
- [x] fix hostPtr function not checking correctly memory bounds
- [x] add MemoryException class
- [x] add MIN_HEAP_ALIGN static constexpr variable to prevent magic value
- [x] add alignUp static constexpr method
- [x] thow MemoryException when unaligned access or unmapped address on read/write methods 
- [x] throw MemoryException when alignment is not a power of two on heapAllocate method
- [x] catch MemoryException too on Interpreter run method

### PR DESCRIPTION
**Pull request by Igoatyouu**

### CODE REVIEW

File: core/src/cpu/interpreter/Interpreter.hpp [hunk 1]
```diff
@@ -78,7 +81,8 @@ namespace Core {
             }
 
         private:
-        public:
+            bool step(Utils::BeDecoder &decoder, const std::uint32_t ppc_pc);
```
Comment (Robouch0) [inline core/src/cpu/interpreter/Interpreter.hpp]: I think it should be noted as [[nodiscard]] since we use the return value in the if from the while loop in run() ?

Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.hpp]: Yeah why not, you are true

File: core/src/exception/Exception.hpp [hunk 2]
```diff
@@ -22,6 +22,8 @@ namespace Core {
 
             ~Exception() override = 0;
 
+            virtual bool isFatal() const { return false; }
```
Comment (Robouch0) [inline core/src/exception/Exception.hpp]: Same here [[nodiscard]] because why not ? I am true ?

File: core/src/cpu/memory/Memory.hpp [hunk 3]
```diff
@@ -18,63 +34,70 @@ namespace Core {
...
 
             [[nodiscard]] std::uint32_t heapAllocate(const std::uint32_t size, std::uint32_t align)
             {
-                if (align < 4)
-                    align = 4;
-                m_heapPtr = (m_heapPtr + align -1) & ~(align - 1);
+                align = std::max(align, MIN_HEAP_ALIGN);
+
+                if (align & (align - 1))
+                    throw MemoryException("[MEM] Heap alignment not a power of two: " + align);
```
Comment (Robouch0) [inline core/src/cpu/memory/Memory.hpp]: Here we should std::format the string like in all the other call to MemoryException, instead of using + on the string

File: core/src/cpu/interpreter/Interpreter.cpp [hunk 4]
```diff
@@ -10,29 +10,40 @@
...
 
 #include "Interpreter.hpp"
-#include "utils/BeDecoder.hpp"
 
 Core::Interpreter::Interpreter(Core::Binary binary) : m_binary(std::move(binary)) { initInstructionMap(); }
 
+bool Core::Interpreter::step(Utils::BeDecoder &decoder, const std::uint32_t ppc_pc)
+{
+    decoder.seek(m_pc);
+    const EncodedInstruction encodedInstruction(decoder.extractSwap<uint32_t>());
```
Comment (Robouch0) [inline core/src/cpu/interpreter/Interpreter.cpp]: We should use std::uint32_t here like in the rest of the file

**Review by Robouch0 — DISMISSED** [review]
Some small things to change, but look good to me overall ! 
Having the step() function make the run() code so much cleanerrr, GG

File: core/src/exception/Exception.hpp (hunk 2 above)
Comment (Igoatyouu) [reply core/src/exception/Exception.hpp]: Yep absolutely! You are true on every of you comments :pray:

File: core/src/cpu/interpreter/Interpreter.cpp [hunk 5]
```diff
@@ -10,29 +10,40 @@
...
+    std::cout << std::format("[PC=0x{:08X}]\t", ppc_pc) << std::bitset<32>(encodedInstruction.raw) << "\t";
```
Comment (NicolasMelet) [inline core/src/cpu/interpreter/Interpreter.cpp]: is this debugging ?

File: core/src/cpu/interpreter/Interpreter.cpp [hunk 6]
```diff
@@ -10,29 +10,40 @@
...
+
 void Core::Interpreter::run()
 {
     auto instructionDecoder = Utils::BeDecoder(m_binary.m_memory.getMemory());
+    std::uint32_t ppc_pc = m_binary.header.e_entry;
 
-    m_pc = m_binary.header.e_entry - Core::Memory::MemoryMap::ApplicationCode;
-    std::cout << "Starting at entrypoint 0x" << m_pc + Core::Memory::MemoryMap::ApplicationCode << std::endl;
+    m_pc = ppc_pc - Core::Memory::MemoryMap::ApplicationCode;
+    std::cout << std::format("[EMU] Starting at entrypoint 0x{:08X}", ppc_pc) << std::endl;
```
Comment (NicolasMelet) [inline core/src/cpu/interpreter/Interpreter.cpp]: if this is some logging information, maybe we could add this code if a MEMORY_LOG macro is set at compilation don't you think ?

File: core/src/cpu/interpreter/Interpreter.cpp [hunk 7]
```diff
@@ -10,29 +10,40 @@
...
-            debugDumpGPR();
-        } catch (Core::InterpreterException &e) {
-            std::cout << e.what() << std::endl;
-        }
+        ppc_pc = m_pc + Core::Memory::MemoryMap::ApplicationCode;
+        if (!step(instructionDecoder, ppc_pc))
+            break;
         m_pc = m_nextPc;
     }
+    std::cout << std::format("[EMU] Exited. PC=0x{:08X}", ppc_pc) << std::endl;
```
Comment (NicolasMelet) [inline core/src/cpu/interpreter/Interpreter.cpp]: same here

File: core/src/cpu/memory/Memory.hpp [hunk 8]
```diff
@@ -18,63 +34,70 @@ namespace Core {
...
+            }
+
             [[nodiscard]] std::uint8_t *hostPtr(const std::uint32_t address) noexcept
             {
                 if (address >= STACK_BASE && address < STACK_BASE + STACK_SIZE)
                     return reinterpret_cast<std::uint8_t*>(m_stack.data() + (address - STACK_BASE));
                 if (address >= m_virtAddress) {
                     const std::size_t offset = address - m_virtAddress;
-                    if (address + offset < m_memory.size())
+                    if (offset < m_memory.size())
```
Comment (NicolasMelet) [inline core/src/cpu/memory/Memory.hpp:61]: curious as to why you removed address + offset in this condition

File: core/src/main.cpp [hunk 9]
```diff
@@ -99,9 +99,6 @@ int main(const int ac, char const *const *av)
 
     Core::Interpreter interpreter(binary);
 
-    interpreter.m_gpr[3] = 2;
-    interpreter.m_gpr[4] = 3;
-
     std::cout << "Loaded module!" << std::endl;
```
Comment (NicolasMelet) [inline core/src/main.cpp:102]: same thing for the logging with a MEMORY_LOG macro

File: core/tests/load/test_lwz.cpp [hunk 10]
```diff
@@ -253,15 +251,15 @@ TEST_F(InstructionTest, LWZ_DoesNotUpdateRA)
...
+    cpu->m_memory.write<uint32_t>(TEST_ADDR + 0x7FFC, 0xBEEFCAFE); // 0x7FFC aligned on 4
     cpu->m_gpr[1] = TEST_ADDR;
 
     EncodedInstruction inst(0);
     inst.rt = 5;
     inst.ra = 1;
-    inst.si = 0x7FFF;
-
-    Core::Instruction::LWZ(*cpu, inst);
+    inst.si = 0x7FFC; // même offset
```
Comment (NicolasMelet) [inline core/tests/load/test_lwz.cpp]: shouldn't we keep comments in english ?

**Review by NicolasMelet — CHANGES_REQUESTED** [review]
looks mostly good

File: core/tests/load/test_lwz.cpp (hunk 10 above)
Comment (Igoatyouu) [reply core/tests/load/test_lwz.cpp]: Yes, you're right!

File: core/src/cpu/memory/Memory.hpp (hunk 8 above)
Comment (Igoatyouu) [reply core/src/cpu/memory/Memory.hpp:61]: Because address + offset will always be higher than the size of the vector

We can't compare the address of something with the size of a vector (It was a mistake)

File: core/src/cpu/interpreter/Interpreter.cpp (hunk 5 above)
Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.cpp]: More basic logging than debugging

File: core/src/cpu/interpreter/Interpreter.cpp (hunk 6 above)
Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.cpp]: Yeah why not :)

File: core/src/cpu/memory/Memory.hpp (hunk 8 above)
Comment (NicolasMelet) [reply core/src/cpu/memory/Memory.hpp:61]: oh my you are right

File: core/src/cpu/interpreter/Interpreter.hpp (hunk 1 above)
Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.hpp]: Done

File: core/src/exception/Exception.hpp (hunk 2 above)
Comment (Igoatyouu) [reply core/src/exception/Exception.hpp]: Done

File: core/src/cpu/memory/Memory.hpp (hunk 3 above)
Comment (Igoatyouu) [reply core/src/cpu/memory/Memory.hpp]: Done

File: core/src/cpu/interpreter/Interpreter.cpp (hunk 4 above)
Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.cpp]: done

File: core/tests/load/test_lwz.cpp (hunk 10 above)
Comment (Igoatyouu) [reply core/tests/load/test_lwz.cpp]: Done

File: core/src/cpu/interpreter/Interpreter.cpp (hunk 6 above)
Comment (Igoatyouu) [reply core/src/cpu/interpreter/Interpreter.cpp]: Done 1ccb2d28f753f481d72ee43efbb9ea4c66464fad

**Review by NicolasMelet — APPROVED** [review]
LGTM
